### ISSUE TITLE
Mac minimising issues

### ISSUE THREAD

**Issue by ZeeCoder** [youtplayer/yout#1]
Once the app is minimised (by clicking "_"), it won't open up again, when clicking on the icon on the dock.

**Comment by daltonmenezes** [comment]
Hi @ZeeCoder . Thank you for letting me know. I believe thats an Electron bug at 1.2.3 version. I'll update Yout for the latest version and fix some issues from this update. I'll be back with news soon.

What's your OsX version?

**Comment by ZeeCoder** [comment]
10.12

**Comment by daltonmenezes** [comment]
@ZeeCoder , please, can you test this build and check if it fix this problem?

> [Link removed]

**Comment by ZeeCoder** [comment]
I'm afraid it's the same still 😔

**Comment by daltonmenezes** [comment]
Oh, man. :(
I'll make some minimal examples running on different versions of Electron, so we can test it and discover if it's an electron or Yout bug. Are you willing to try to help me with this? I don't have a Mac, unfortunately I just doing it on a virtual machine and it's not the same thing.

**Comment by ZeeCoder** [comment]
sure

**Comment by daltonmenezes** [comment]
@ZeeCoder , before the minimal examples, let's try a few things:

Move Yout.app to Applications folder. Open Yout and hit the right click on the Yout icon on the dock and set 'keep in dock'. Restart Yout and check if the minimize issue continues.

**Comment by daltonmenezes** [comment]
@ZeeCoder , This will not work ( about my previous comment). For now, I believe the solution is in here:

```
Event: ‘activate’ - macOS

Emitted when the application is activated, which usually happens 
when the user clicks on the application’s dock icon.
```

From Electron Documentation.

I'm working now for implement this in Yout. I'll be back soon bringing the new build for tests.

**Comment by daltonmenezes** [comment]
@ZeeCoder , please,  test this build:

> [Link removed]

**Comment by ZeeCoder** [comment]
Hi @daltonmenezes, sorry for the late reply!
Unfortunately it still does the same thing. :(
I open it, minimise it and then I can't maximise it anymore. :/

**Comment by daltonmenezes** [comment]
@ZeeCoder , no problem. :)
Well, there's no way to fix it if I keep doing it on a virtual machine. I'll try to rescue an old PC here and try to install a OS X in it. haha, Pentium dual core 3.40GHz, 2GB, Geforce 512MB, we must pray about it haha.

**Comment by ZeeCoder** [comment]
Thanks for the effort btw, don't feel too pressured though I kinda think you did more than can be expected already 👍

**Comment by daltonmenezes** [comment]
Thanks @ZeeCoder . I have good news! About installing OS X in the old PC, it did not work. I've installed on my main PC and was great even being painful.  haha

The good news is that I've identified the problem. A quick trick to solve this at the operating system level is: 

```
1. Go to System Preferences / Dock.
2. Disable "Minimize windows into application icon".
```

Done!

Test it and let me know if it works for you. The next step is fix it at the code level for work with "Minimize windows into.." option enabled. Now with OS X working without a VM will be more easily. :)

**Comment by ZeeCoder** [comment]
Yeah that works, but I don't like that behaviour unfortunately :D

**Comment by daltonmenezes** [comment]
I get it. :D
But it'll be much easier now to get a fix for it. I hope to come back soon with the solution.

**Comment by daltonmenezes** [comment]
@ZeeCoder Good news. It's solved! :)
[See and download it from here.](https://github.com/youtplayer/yout/blob/master/CHANGELOG.md)

**Comment by ZeeCoder** [comment]
Awesome, it really works!
What was the issue?

**Comment by daltonmenezes** [comment]
It's an always on top bug from Electron. If you minimize with it enabled, the window restauration doesn't work anymore. I've discover that when I's created a minimal example and I's tested the possibilities. But that was good, because I enjoyed it and made other improvements from that. I've reported this bug for Electron team, but no answers about it yet.

Now you can enjoy Yout. Any problem or suggestions for improvement, it'll be great having your feedback. Have a good time, @ZeeCoder and thanks for helping me in this issue.
