### ISSUE TITLE
"Full screen is unavailable" message don't let me open the list of videos in YouTube playlist button.

### ISSUE THREAD

**Issue by prototype23** [youtplayer/yout#2]
This started to happen 30/11/2016. Youtube is placing a button over playlist button. So you can't select a video from the playlist.

![yout](https://cloud.githubusercontent.com/assets/14275025/20776125/5f046418-b767-11e6-875a-4a492b4b4259.jpg)

A quick walkaround is to click two times in the video to enter in fullscreen mode and repeat it to exit the fullscreen. The message then will be hided.

**Comment by daltonmenezes** [comment]
Hi @prototype23 . Thanks for reporting. 

It's an YouTube bug as you can see in [here](https://productforums.google.com/forum/#!msg/youtube/Y-i1bXFvHaA/P_-GA3GBCgAJ;context-place=msg/youtube/nm14udpfmw4/d2HOHgqqCgAJ) and [here](https://productforums.google.com/forum/#!topic/youtube/VUDpzEwhedQ). Even the YouTube demo player is affected too as you can see in [here](https://developers.google.com/youtube/youtube_player_demo).

For now *'the click two times'* trick is the palliative solution until YouTube fix it.

**Comment by Luckino** [comment]
You could also delete or hide the div with class "ytp-popup" when loading the url

**Comment by daltonmenezes** [comment]
@Luckino , Thanks for the tip. I don't know if it's allowed using Electron for changing a cross domain content even locally, I'll search for that, but anyway I've fixed it. I'm preparing the file for you guys replace it.

>  Do you like Yout? Please, make a donation using [paypal](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=dvicer%40gmail%2ecom&lc=US&item_name=Dalton%20Menezes&item_number=Yout&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donateCC_LG%2egif%3aNonHosted) or [pagseguro](https://pag.ae/blZmhm). Your support is very important.

**Comment by daltonmenezes** [comment]
# How to fix #2

Download it:

[yout-fullscreen-message-fix.zip](https://github.com/youtplayer/yout/files/627585/yout-fullscreen-message-fix.zip)

Extract this file in **Yout folder/resources/app/app/**
And confirm this file replacement. Open Yout and check if it was fixed.

**This issue remains open until the files from website for download will be updated.**

>  Do you like Yout? Please, make a donation using [paypal](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=dvicer%40gmail%2ecom&lc=US&item_name=Dalton%20Menezes&item_number=Yout&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donateCC_LG%2egif%3aNonHosted) or [pagseguro](https://pag.ae/blZmhm). Your support is very important.
