### ISSUE TITLE
Provide binary release via GitHub / Homebrew

### ISSUE THREAD

**Issue by rogeriopradoj** [youtplayer/yout#3]
Hello!

Is it possible start providing the releases via GitHub as well? This way we could make it installable via [Homebrew](http://brew.sh/).

Thanks!

**Comment by daltonmenezes** [comment]
Hi @rogeriopradoj . I'm sorry for the late reply.

Yes, It's possible. At this moment I'm on vacation in another state and my internet connection in here isn't good, as soon as I back to Rio de Janeiro I'll do it. Ok? This issue keeps open until there.

Thanks for the great suggestion.

>  Do you like Yout? Please, make any [donation](https://youtplayer.github.io/#footer). I'm an indie developer and your support is very important.

**Comment by fortiko** [comment]
Hello! I am not sure where to find the current release on github: could you please point out the URL? This would make the project also a lot more trustworthy than a Mediafire download. Thanks!

**Comment by daltonmenezes** [comment]
Hello @fortiko , please check out [here](https://github.com/youtplayer/yout/releases)  

>  Do you like Yout? Please, make any [donation](https://youtplayer.github.io/#footer). I'm an indie developer and your support is very important for the project continuation.
