### ISSUE TITLE
right click on header not working on gnome

### ISSUE THREAD

**Issue by jaswdr** [youtplayer/yout#6]
On gnome windows you have some options like "Always on top" who are interesting for the player, I see that this doesn't works, are you activelly blocking it or this some side effects ?

**Comment by daltonmenezes** [comment]
It's a side effect, because Yout use frameless window. The Always on top option is activated by default, but gnome don't allow this behavior as I saw. I'm working on Yout 2.0 and I'll try to fix this behavior on gnome windows. The Yout 2.0 source code will be in here too for contributions.

**Comment by jaswdr** [comment]
@daltonmenezes awesome, I'll appreciate to contribute to this project too 😄
