### ISSUE TITLE
This is fake!

### ISSUE THREAD

**Issue by mbnoimi** [youtplayer/yout#7]
Since more than one year the developer didn't publish the source code which make me thinking about a nasty embeded code!

Even he/she didn't publish the binaries here!!!

**Comment by daltonmenezes** [comment]
I'm sorry, but you wrong. As I said [here](https://github.com/youtplayer/yout#wheres-the-code) : 

> I'm currently working in v2.0, so the code will be available here when I release it. But, it's an Electron app, you have the code when you download Yout, ok?

If you have doubts check your downloaded files.
