### ISSUE TITLE
How to install Yout on Ubuntu

### ISSUE THREAD

**Issue by angelkurten** [youtplayer/yout#9]
How to install in ubuntu

**Comment by daltonmenezes** [comment]
Yout is portable. Just download,  extract the zip file and inside the folder run Yout file.

**Comment by angelkurten** [comment]
I have this error

`./Yout: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory`

**Comment by daltonmenezes** [comment]
@angelkurten please, try it on terminal:

sudo apt -y install libgconf2-4

**Comment by TrySpace** [comment]
* `libgconf-2-4`
